version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    environment:
      - UMASK=0002
    command: >
      sh -c "chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
             chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
             while ! mysqladmin ping -h mysql --silent; do
               echo 'Waiting for MySQL...'; sleep 2;
             done &&
             php artisan migrate:fresh --seed &&
             docker-php-entrypoint php-fpm"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: product_service
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
